config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000
  resources :stations do
    member do
      post 'claim' => 'stations#claim'      # => 'stations#claim', as: 'claim_river'
      post 'unclaim' => 'stations#unclaim'
    end
    collection do
      get 'favorites' => 'stations#favorites'
    end
  end

  root 'stations#index'

  get 'stations/favorite_stations' => 'stations#claim'
  get 'pages/about', as: 'about'
  get 'pages/contact', as: 'contact'
  get 'pages/home', as: 'home'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:new, :create]

  mount Resque::Server.new, at: "/resque"
  get 'verification/:token', to: 'users#verify', as: 'verify_email'

end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :forecasts
  has_many :flow_readings
  has_many :favorite_stations
  has_many :users, through: :favorite_stations

  # Pagination

  self.per_page = 10

  def favorite(user)
    favorite_stations.first_or_create(user: user) # { |favorite_station|}
  end

  def remove_favorite(user)
      favorite_stations.where(user: user).destroy_all
  end

  validates :code, uniqueness: true, presence: true, numericality: {only_integer: true}
  validates :name, presence: true
  validates :longitude, numericality: true
  validates :latitude, numericality: true
# validates :stream_flow, presence: true

  def current_forecast
    @current_forecast ||= ForecastIO.forecast(latitude, longitude)
  end

  def current_summary
    current_forecast.currently.summary
  end

  def current_temp
    current_forecast.currently.temperature
  end

  def forecast_at(date)
    forecasts.where(date: date).order(created_at: :desc).first
  end

  def flow_rate
    first_reading = flow_readings.first
    if first_reading
      first_reading.flow_rate
    end
  end

  def favorite?(user)
    favorite_stations.where(user: user).count > 0
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy, :claim, :unclaim]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.joins(:flow_readings).order('flow_readings.flow_rate DESC').uniq

    @stations_paginated = Station.joins(:flow_readings).order('flow_readings.flow_rate DESC').uniq.paginate(page: params[:page])

    @hash = Gmaps4rails.build_markers(@stations) do |station, marker|
      marker.lat station.latitude.to_f
      marker.lng station.longitude.to_f
      marker.infowindow render_to_string(:partial => "/layouts/partials/infowindow", :locals => { :station  => station})
    end
  end

  def favorites
    @stations = current_user.stations

    @stations_paginated = current_user.stations.paginate(page: params[:page])

    @hash = Gmaps4rails.build_markers(@stations) do |station, marker|
      marker.lat station.latitude.to_f
      marker.lng station.longitude.to_f
      marker.infowindow render_to_string(:partial => "/layouts/partials/infowindow", :locals => { :station  => station})
    end
  end


  # GET /stations/1
  # GET /stations/1.json
  def show
    @hash = Gmaps4rails.build_markers(@station) do |station, marker|
      marker.lat station.latitude.to_f
      marker.lng station.longitude.to_f
      marker.infowindow station.name + "&nbsp;&nbsp;&nbsp;"
    end
    @dates = Date.today..(Date.today+7.days)
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  def claim
    if current_user
      @favorite_station = FavoriteStation.new
      @favorite_station.user_id = current_user.id
      @favorite_station.station_id = @station.id
      @favorite_station.save
      current_user.update_email
      redirect_to root_path,
        notice: "Station has been added to your favorites"
    else
      redirect_to new_user_path,
      notice: "You must be logged in to choose a favorite"
    end
   # @station.favorite(current_user)


      # if current_user
      # binding.pry
      # current_user.favorite_station << @stations
      # redirect_to root_path, notice: "#{@favorite_station} has been added to your list"
      # end
  end

  def unclaim
    @station.remove_favorite(current_user)
    redirect_to root_path,
      notice: 'Station has been removed from your favorites'
  end

# Station.find(params['id']) find a station with a given ID
  # if not found - return a message 'Station not found / error message'
  # if it is found, then it ads the found station to 'favorite stations'
  # when adding found station to 'favorite stations'
  # user ID comes from = current_user
  # station ID comes from = found station (.find gave us this ID)
  # if it works return "Success!"
  # if not, return "unable to claim"

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end
end



private
# Use callbacks to share common setup or constraints between actions.
def set_station
  @station = Station.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def station_params
  params.require(:station).permit(:name, :latitude, :longitude)
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @station.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h4>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :latitude, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :code, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :code, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/stations/_list.html.erb
<div class="page-header">
  <!-- Google Maps -->
  <div align="center" style="width: 100%; margin-bottom: 4em; ; margin-top: 1em;">
    <div id="map" style='width: 60em; height: 42em;'></div>
  </div>

  <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({provider: {}, internal: {id: 'map'}}, function() {
          markers = handler.addMarkers(<%=raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(7)
      });

  </script>
  <!-- End Google Maps -->


  <h1>Listing stations</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th style="width: 3em;">Today's Weather</th>
      <th>Most Recent Reading</th>
      <th>Flow Rate</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @stations_paginated) do |station| %>
        <%= render partial: 'stations/station', locals: {station: station, user: @user} %>
        <td>
          <% if station.favorite?(current_user) %>
              <%= button_to 'Unclaim', unclaim_station_path(station) %>
          <% else %>
              <%= button_to 'Claim', claim_station_path(station) %>
          <% end %>
        </td>
    <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @stations_paginated, renderer: BootstrapPagination::Rails %>

app/views/stations/_station.html.erb
<div dom_id(station)>
  <td><%= link_to station.name, station %></td>
  <td><%= fmt_coord station.latitude.to_f %></td>
  <td><%= fmt_coord station.longitude.to_f %></td>
  <td style="width: 3em;">
    <% if station.forecasts.any? %>
        <strong>High: </strong> <%= number_with_precision(station.forecasts.first.maxtemp, precision: 2) %> &deg;F<br/>
        <strong>Low: </strong><%= number_with_precision(station.forecasts.first.mintemp.to_f, precision: 2) %> &deg;F

    <% end %>
  </td>
  <td><%= station.flow_readings.first.date_time.in_time_zone.strftime("%A %e %B %Y,%I:%M:%S %Z") %></td>
  <td><%= format_flow_rate station.flow_readings.first.flow_rate %></td>
</div>

app/views/stations/edit.html.erb
<div class="page-header">
  <%= link_to stations_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @station, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing station</h1>
</div>

<%= render 'form' %>

app/views/stations/favorite_stations.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Current Weather</th>
      <th>Flow Rate</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @favorites) do |station| %>
      <div dom_id(station)>
        <td><%= station.name %></td>
        <td><%= fmt_coord station.latitude %></td>
        <td><%= fmt_coord station.longitude %></td>
        <td><% station.weather[:temperature]  %><br/><= station.weather[:summary] %></td>
        <td><%= format_flow_rate station.flow_rate %></td>
        <td><%= link_to 'Claim River', claim_station_path(station) %></td>
      </div>
    <% end %>
    </tbody>
  </table>
</div>

app/views/stations/favorites.html.erb
<%= render 'list' %>

app/views/stations/index.html.erb
<div class="page-header">
  <!-- Google Maps -->
  <div align="center" style="width: 100%; margin-bottom: 4em; ; margin-top: 1em;">
    <div id="map" style='width: 60em; height: 42em;'></div>
  </div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({provider: {}, internal: {id: 'map'}}, function() {
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(7)
    });

  </script>
  <!-- End Google Maps -->


  <h1>Listing stations</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th style="width: 3em;">Today's Weather</th>
      <th>Most Recent Reading</th>
      <th>Flow Rate</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%= content_tag_for(:tr, @stations_paginated) do |station| %>
        <%= render partial: 'stations/station', locals: {station: station, user: @user} %>
        <td>
          <% if station.favorite?(current_user) %>
              <%= button_to 'Unclaim', unclaim_station_path(station) %>
          <% else %>
              <%= button_to 'Claim', claim_station_path(station) %>
          <% end %>
        </td>
    <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @stations_paginated, renderer: BootstrapPagination::Rails %>

app/views/stations/new.html.erb
<div class="page-header">
  <%= link_to stations_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New station</h1>
</div>

<%= render 'form' %>

app/views/stations/show.html.erb
<div class="page-header">
  <%= link_to stations_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>

  <h1><%= @station.name.titleize %></h1>
</div>
<% if @station.favorite?(current_user) %>
  <span class="glyphicon glyphicon-heart"></span>
<% end %>

<dl class="dl-horizontal">
  <div style="float: left; margin-right: 3em;">
    <dt>Latitude:</dt>
    <dd><%= fmt_coord number_with_precision(@station.latitude, precision: 4) %></dd>
    <dt>Longitude:</dt>
    <dd><%= fmt_coord number_with_precision(@station.longitude, precision: 4) %></dd>
  </div>
  <div style="float: left;">
    <dt>Current Weather:</dt>
    <dd><%= number_with_precision(@station.current_temp, precision: 2) %> &deg;F <br/>
      <%= @station.current_summary %>
    </dd>
    </dt>
  </div>
</dl>

<div style="clear:both"></div>

<!-- Google Maps -->
<div align="center" style="width: 100%; margin-bottom: 100px; ; margin-top: 2em;">
  <div id="map" style='width: 65em; height: 30em;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({provider: {}, internal: {id: 'map'}}, function() {
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds(markers);
    handler.getMap().setZoom(10)
  });

</script>


<!-- End Google Maps -->

</dl>

<div>

  <h3>Flow Reading</h3>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
      <tr>
        <th>Date</th>
        <th>Flow Rate</th>


      </tr>
      </thead>
      <tbody>
      <% @station.flow_readings.last(10).each do |reading| %>
        <% if @station.flow_readings.any? %>
          <tr>
            <td><%= reading.date_time.in_time_zone.strftime("%A %e %B %Y,%I:%M:%S %Z") %></td>
            <td><%= format_flow_rate reading.flow_rate %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    <br/>
    <br/>

    <h3>Forecast:</h3>
    <br/>

    <div style="width: 100%; clear: both; margin-left: 2em;">
      <% @dates.each_with_index do |date, index| %>
        <% if index % 4 == 0 %>
          <div style="clear: both;"></div>
        <% end %>
          <% forecast = @station.forecast_at(date) %>
          <% if @station.forecasts.any? %>
            <div style="width: 230px; margin-left: 1em; margin-bottom: 2em; padding-bottom: 1em; padding-left: 1em; padding-right: 1em; float: left; border-style: dotted; border-width: 1px; border-color: #dddddd">
              <dd style="margin-bottom: 10px; text-align: center">
                <h4><strong><%= forecast.date.strftime("%A, %B %e") %></strong></h4></dd>
              <dd><strong>High:</strong> <%= number_with_precision(forecast.maxtemp, precision: 2) %> &deg;F</dd>
              <dd style="margin-bottom: 10px">
                <strong>Low:</strong> <%= number_with_precision(forecast.mintemp, precision: 2) %> &deg;F
              </dd>
              <dd style="margin-bottom: 6px; width: 86%;"><%= forecast.summary %></dd>
            </div>
          <% end %>

      <% end %>
    </div>
  </div>
</div>