config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000
  resources :stations do
    member do
      post 'claim' => 'stations#claim'      # => 'stations#claim', as: 'claim_river'
      post 'unclaim' => 'stations#unclaim'
    end
    collection do
      get 'favorites' => 'stations#favorites'
    end
  end

  root 'stations#index'

  get 'stations/favorite_stations' => 'stations#claim'
  get 'pages/about', as: 'about'
  get 'pages/contact', as: 'contact'
  get 'pages/home', as: 'home'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:new, :create]

  mount Resque::Server.new, at: "/resque"
  get 'verification/:token', to: 'users#verify', as: 'verify_email'

end

app/views/user_notifier/favorite_updates.html.erb
Hello <%= @user.first_name.titleize %>,

<p/>
Here are your favorite station readings for the day:
<p/>
<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th style="width: 3em;">Today's Weather</th>
    <th>Most Recent Reading</th>
    <th>Flow Rate</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <%= content_tag_for(:tr, @stations) do |station| %>
      <%= render partial: 'stations/station', locals: {station: station, user: @user} %>
    <% end %>
  </tbody>
</table>

app/views/user_notifier/signed_up.html.erb
Hello <%= @user.first_name.titleize %>,

You recently created a <%= t('site_name') %> account
<p/>
using your email address of <%= @user.email %>.
<p/>
To verify your email address, please open the following link:
<p/>
<%= link_to verify_email_url(@user.token), verify_email_url(@user) %>
<p/>
If the link does not work, please login to your account
and enter this token:
<p/>
<%= @user.token %>
<p/>
Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/signed_up.text.erb
Hello <%= @user.first_name.titleize %>,

You recently created a <%= t('site_name') %> account
<p/>
using your email address of <%= @user.email %>.
<p/>
To verify your email address, please open the following link:
<p/>
<%= link_to verify_email_url(@user.token), verify_email_url(@user) %>
<p/>
If the link does not work, please login to your account
and enter this token:
<p/>
<%= @user.token %>

Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/verified.html.erb
Hello <%= @user.first_name.titleize %>,
<p/>
You recently created a <%= t('site_name') %> account
<p/>
using your email address of <%= @user.email %>.
<p/>
To verify your email address, please open the following link:
<p/>
<%= verify_email_url(@user.token) %>
<p/>
If the link does not work, please login to your account
and enter this token:
<p/>
<%= @user.token %>
<p/>
Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/verified.text.erb
Hello <%= @user.first_name.titleize %>,
<p/>
You recently created a <%= t('site_name') %> account
<p/>
using your email address of <%= @user.email %>.
<p/>
To verify your email address, please open the following link:
<p/>
<%= verify_email_url(@user.token) %>
<p/>
If the link does not work, please login to your account
and enter this token:
<p/>
<%= @user.token %>
<p/>
Thank you for visiting <%= t('site_name') %>.

app/views/user_notifier/welcome.html.erb
Hello <%= @user.first_name.titleize %>,

Thank you for signing up for a <%= t('site_name') %> account
using your email address of <%= @user.email %>.
<p/>
We hope you will find it useful in your Colorado fly fishing adventures.
<p/>
<%= t('site_name') %>.

app/views/user_notifier/welcome.text.erb
Hello <%= @user.first_name.titleize %>,

Thank you for signing up for a <%= t('site_name') %> account
using your email address of <%= @user.email %>.
<p/>
We hope you find it useful in your fly fishing adventures.
<p/>
<%= t('site_name') %>.