config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000
  resources :stations do
    member do
      post 'claim' => 'stations#claim'      # => 'stations#claim', as: 'claim_river'
      post 'unclaim' => 'stations#unclaim'
    end
    collection do
      get 'favorites' => 'stations#favorites'
    end
  end

  root 'stations#index'

  get 'stations/favorite_stations' => 'stations#claim'
  get 'pages/about', as: 'about'
  get 'pages/contact', as: 'contact'
  get 'pages/home', as: 'home'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:new, :create]

  mount Resque::Server.new, at: "/resque"
  get 'verification/:token', to: 'users#verify', as: 'verify_email'

end

app/views/layouts/_authentication.html.erb
<% if current_user %>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
        <%= "#{current_user.first_name} #{current_user.last_name}" %><span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
<li><%= link_to 'Favorites', favorites_stations_path %></li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      </ul>
    </li>
<% else %>
    <li><%= link_to 'Sign up', new_user_path %></li>
    <li><%= link_to 'Log in', login_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Flyarado", root_path, :class => "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= current_page?(root_path) ? 'active' : ''%>"><%= link_to 'Home', root_path %></li>
        <li class="<%= current_page?(about_path) ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
        <li class="<%= current_page?(contact_path) ? 'active' : '' %>"><%= link_to 'Contact', contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/authentication' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Flyarado</title>
  <%= render 'layouts/navigation' %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Begin Google Maps JS-->
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
  <!-- End -->
</head>
<body>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>